### ISSUE TITLE
UK Biobank GWAS Results

### ISSUE THREAD

**Issue by andronekomimi** [weizhou0/GATE#1]
Hello,

There is no section **UK Biobank GWAS Results** in the README page.
How could we access to GATE results ?

Thank you very much

**Comment by weizhou0** [comment]
Hi Audrey,

I'm sorry for the confusion. We are depositing our summary stats to
dropbox. We will put the link to gate.genohub.org and our pre-print to
biorxiv within this week.

Thanks,
Wei

**Comment by andronekomimi** [comment]
Hi Wei,

Thank you for your quick response and great talk today !

Did you know that your link gate.genohub.org was redirecting to the FAVOR interface https://favordev.shinyapps.io/favor/ ? I’ve just discovered a new tool :-D

Thanks,
Audrey

**Comment by weizhou0** [comment]
Hi Audrey,
FAVOR is a great annotation tool.  We pointed to FAVOR before creating the
webpage for the link:)
Currently the gate.genohub.org is up with summary stats of UKBB and our
pre-print is on bioRxiv.

https://www.biorxiv.org/content/10.1101/2020.10.31.358234v1

Thanks!

Wei

**Comment by laurendonoghue** [comment]
Hello, 

The links provided in the manuscript for access to the GWAS results (http://gate.genohub.org/ and http://phewas.genohub.org/) are not currently working for me. 

Is there an updated way to access the data?

Thanks, 

Lauren
