### ISSUE TITLE
Error in if (abs(q - m1)/sqrt(var1) < Cutoff) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by xinxwang** [weizhou0/GATE#10]
Hi Wei,

Thanks for developing such a fantastic tool! I tried to use it to run an incident disease GWAS but encountered an error that I didn't know how to solve. I used the docker image you shared for this analysis.

I've pasted the last few lines of the log file here:

dim(X1):  39986 23 
length(V):  39986 
      user     system    elapsed 
640621.673    106.476 640833.614 
t_end - t_begin, fitting the NULL model took
      user     system    elapsed 
640612.117     88.374 640804.397 
Start estimating variance ratios

Family: binomial 
Link function: logit 

[1] FALSE
dim(Rmat):  39986 5 
dim(sqrtWinvN):  39986 39986 
dim(sqrtWinvNR):  39986 5 
dim(Dinv):  5 5 
dim(RNWNR):  5 5 
dim(ACm):  5 5 
dim(WinvN):  39986 39986 
dim(Rmat):  39986 5 
dim(WinvNRt):  39986 5 
dim(ACinv):  5 5 
Only one variance ratio will be estimated using randomly selected markers with MAC >= 20
[1] "HERE6"
iter from getPCG1ofSigmaAndVector 25
iter from getPCG1ofSigmaAndVector 192
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 19
iter from getPCG1ofSigmaAndVector 32
iter from getPCG1ofSigmaAndVector 8
iter from getPCG1ofSigmaAndVector 3
iter from getPCG1ofSigmaAndVector 68
iter from getPCG1ofSigmaAndVector 20
iter from getPCG1ofSigmaAndVector 15
iter from getPCG1ofSigmaAndVector 61
iter from getPCG1ofSigmaAndVector 25
iter from getPCG1ofSigmaAndVector 17
iter from getPCG1ofSigmaAndVector 47
iter from getPCG1ofSigmaAndVector 13
iter from getPCG1ofSigmaAndVector 26
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 17
iter from getPCG1ofSigmaAndVector 61
iter from getPCG1ofSigmaAndVector 42
iter from getPCG1ofSigmaAndVector 14
iter from getPCG1ofSigmaAndVector 164
iter from getPCG1ofSigmaAndVector 38
507816 th marker
G0 0 0 0 0 0 0 0 0 0 0 
iter from getPCG1ofSigmaAndVector 52
var1 is  NaN 
Error in if (abs(q - m1)/sqrt(var1) < Cutoff) { : 
  missing value where TRUE/FALSE needed
Calls: fitNULLGLMM -> scoreTest_SPAGMMAT_forVarianceRatio_binaryTrait
Execution halted

It would be great if you could help with this. Thank you!!

Best,
Xin

**Comment by weizhou0** [comment]
Hi @xinxwang, 

Could you please try the newest version and see if the issue has been fixed? Please feel free to re-open the issue if not.

Thanks,
Wei
