### ISSUE TITLE
Where is the appropriate place to specify censored data?

### ISSUE THREAD

**Issue by nathansharris** [weizhou0/GATE#11]
In SAIGE I believe the phenoCol flag specifies the column containing the phenotype of interest in the phenotype file. However, in GATE, the time to event is the phenotype of interest but is specified using the eventTimeCol flag. When running GATE, should the name of the column containing censoring data (0's and 1's) be provided to the phenoCol argument? If not, how is censoring data passed to GATE?

Thank you!

**Comment by alldayscientess** [comment]
Interested in this answer too!

**Comment by weizhou0** [comment]
Hi @nathansharris and @alldayscientess, 

 phenoCol is used to pass the censoring status (0 for censor, 1 for event). 

Thanks,
Wei
