### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by aprilhartley** [weizhou0/GATE#12]
Hello
I am getting the following error message when trying to install GATE using conda (I am not able to install via docker):
"Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz
Failed to build package statgen/savvy
ERROR: configuration failed for package 'SAIGE'

Our HPC expert had the following advise:
"During the build it tries to download version 1.2.11 of zlib from:
http://zlib.net/zlib-1.2.11.tar.gz
however, this version doesn't exist at that location.
The current version is:
http://zlib.net/zlib-1.2.12.tar.gz
Unfortunately I can't find where the version is specified in the GATE source
so I can't change it to a working version."

Can you please advise where the specific version number is defined and how to change it please?

**Comment by WZo0o** [comment]
Hi,
I installed GATE through conda and I have the same issue. Did you ever find a fix? @aprilhartley
