### ISSUE TITLE
installation error;xiaoyeli/superlu

### ISSUE THREAD

**Issue by LivUllmann** [weizhou0/GATE#13]
Hello!

I have tried installing GATE in R but get message:
install.packages("GATE_0.42.tar.gz",  repos = NULL, type="source")

Failed to build package xiaoyeli/superlu
ERROR: configuration failed for package ‘GATE’
* removing ‘/home/karpat@ad.cmm.se/anaconda3/envs/RSAIGE2/lib/R/library/GATE’
Thank you!

**Comment by weizhou0** [comment]
Hello @LivUllmann, 

The easiest way to install in using the conda environment. Please see our updated conda env file and the steps.

https://github.com/weizhou0/GATE#install-gate-using-the-conda-environment

Thanks,
Wei
