### ISSUE TITLE
GATE calls itself SAIGE and thus can't be installed in parallel with SAIGE

### ISSUE THREAD

**Issue by dvg-p4** [weizhou0/GATE#17]
https://github.com/weizhou0/GATE/blob/556a6719dccc10cede6d37e6f571816e9b90720b/DESCRIPTION#L1-L3

This prevents installing both SAIGE and GATE into an R library since they will overwrite each other.

**Comment by weizhou0** [comment]
Hi @dvg-p4, 

Sorry about the confusion. To avoid the conflict, you will need to install it to a different directory. We will fix this soon. 

Thanks,
Wei
