### ISSUE TITLE
The number of samples specified in the sample file does not equal to the number of samples in the VCF

### ISSUE THREAD

**Issue by hongzheduan** [weizhou0/GATE#35]
Hi, Wei

I tried both GATE v0.45 and 0.44 docker image for survival analysis on UKB RAP platform. The first step looks good, and I got result, but for the second step, with the following setting, 

step2_SPAtests.R \
--vcfFile=/analysis_input/final_qc_vcf2.vcf.gz \
--vcfFileIndex=/analysis_input/final_qc_vcf2.vcf.gz.tbi \
--vcfField=GT \
--minMAF=0.0001 \
--minMAC=1 \
--sampleFile=/analysis_input/sample_list.txt \
--GMMATmodelFile=/analysis_output/gate_step1_output.rda \
--varianceRatioFile=/analysis_output/gate_step1_output.varianceRatio.txt \
--SAIGEOutputFile=/analysis_output/gate_step2_output.txt \
--numLinesOutput=2 \
--IsOutputAFinCaseCtrl=TRUE \
--IsOutputNinCaseCtrl=TRUE \
--IsSPAfast=FALSE 

I consistently received Error message below

WARNING: Open VCF failed
Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex, :
  ERROR! The number of samples specified in the sample file does not equal to the number of samples in the VCF file
Please check again. Please note that the sample file needs to have no header.
Execution halted

Can you guide me how to solve this? I am pretty sure the numbers in the sample file and the VCF file are the same.
To create vcf file, i used:
./plink --bfile final_qc --recode vcf --out final_qc_vcf 

In this step the subject ID became familyID_SubjectID, so I used the following code to convert 
grep "^#CHROM" final_qc_vcf.vcf | cut -f10- | tr '\t' '\n' |
awk 'BEGIN{FS=OFS="\t"}{split($1,a,"_");print $1,a[2]}' > sample_name_chage.txt
bcftools reheader -s sample_name_chage.txt -o final_qc_vcf2.vcf final_qc_vcf.vcf

To get .gz and index file, I used
bcftools view final_qc_vcf2.vcf -Oz -o final_qc_vcf2.vcf.gz
bcftools index --tbi final_qc_vcf2.vcf.gz

To get sample file, I used
grep "^#CHROM" final_qc_vcf2.vcf | cut -f10- | tr '\t' '\n' > sample_list.txt

Thanks
Hongzhe

**Comment by jeffchen2000** [comment]
I got the same issue when I use bgen files as input, and the sample file is generated by plink2 along with the bgen file.

Error in SPAGMMATtest(vcfFile = opt$vcfFile, vcfFileIndex = opt$vcfFileIndex,  :
  ERROR! The number of samples specified in the sample file does not equal to the number of samples in the bgen file

here are my scripts:
apptainer run --bind $PWD:/mnt/saige docker://wzhou88/saige.survival:0.45 step2_SPAtests.R \
        --bgenFile=/mnt/saige/genotypes.bgen \
        --bgenFileIndex=/mnt/saige/genotypes.bgen.bgi \
        --sampleFile=/mnt/saige/genotypes.sample \
        --SAIGEOutputFile=/mnt/saige/output/single_snv_survival/genotype_100markers_marker_bgen_Firth_chr1.txt \
        --chrom=1 \
        --minMAF=0 \
        --minMAC=20 \
        --GMMATmodelFile=/mnt/saige/output/single_snv_survival/example_binary_single_snv.rda \
        --varianceRatioFile=/mnt/saige/output/single_snv_survival/example_binary_single_snv.varianceRatio.txt \
        --LOCO=TRUE

when remove the first two head lines from the *.sample file:
ID_1 ID_2 missing sex
0 0 0 D

it worked!

**Comment by hongzheduan** [comment]
Thanks. I apologize for the late response. Following your suggestions by using bgen files as input generated by Plink2 and removing the first two lines from .sample file, I finally get rid of the errors! Unfortunately, I still can't get any results. My variance ratio file from step 1 only has one number, is that correct? Can you share your code for Step 1? Thanks a billion!

**Comment by hongzheduan** [comment]
Ok. I believe I have figured this out. Thanks for your help!
