### ISSUE TITLE
adjust for categorical covariates

### ISSUE THREAD

**Issue by lisongmiller** [weizhou0/GATE#4]
Hi there,

Thanks for developing this nice tool!
I would like run a GWAS for time to event outcome, and adjusting several covariates, including nominal covariates. And I notice there is a flag "--covarColList=COVARCOLLIST" in docker image, which is different from SAIGE. I am not sure whether GATE supports for adjusting nominal covariates?

If not, I learnt that for linear regression, you can regress all covarites then use residual for GWAS. Is there a similar way for survival analysis? Thank you!
{
For example, in R
fit = lm(phenotype ~ covariates, data)
corrected_phenotype = resid(fit) 
}

Best,
Song

**Comment by weizhou0** [comment]
Hi Song,

Thanks for using GATE! --covarColList is the same as SAIGE and currently
GATE does not support the categorical covariates automatically. You will
need to write the  different categories to different columns in the
covariate file.
GATE does not support regressing out covariates first, but we will
implement a similar option soon.

Thanks,
Wei

**Comment by lisongmiller** [comment]
Hi Wei,

Thanks for you reply, very helpful!
Mind if I ask the approximate date of new GATE repository release. If just a couple of weeks then I would rather wait for it.

Best,
Song
