### ISSUE TITLE
Error in loadNamespace(name) : there is no package called ‘lintools’

### ISSUE THREAD

**Issue by mathiasS-hub** [weizhou0/GATE#7]
Hi,
I am running the latest version of GATE 0.42 that we pulled using the docker image. It runs well and creates the .rda file, but thereafter it returns an error at Step 1;
**Error in loadNamespace(name) : there is no package called ‘**lintools**’**
Calls: fitNULLGLMM ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

I am using the following commands;

module load singularity/3.7.1
/working/geX/share/containers/singularity/saige.survival-0.42.sif step1_fitNULLGLMM.R \
        --plinkFile=${plinkFile} \
        --phenoFile=${phenoFile} \
        --phenoCol=${trait} \
        --covarColList=Age,Sex,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10 \
        --sampleIDColinphenoFile=IID \
        --eventTimeCol=FU_Time_CM_Death \
        --eventTimeBinSize=1\
        --traitType=survival \
        --outputPrefix=${dir}/${trait_suffix} \
        --LOCO=FALSE \
        --nThreads=${ncpus} 

Our R version already has the package **lintools**

How can I get around this issue?
Cheers,
Mathias

**Comment by sabrinacamp2** [comment]
I'm having this same issue. Did you ever find a fix? @mathiasS-hub

**Comment by weizhou0** [comment]
Hi all,

Apologize for the late reply. I just pushed the 0.42 docker image again
with the lintools library installed.
Could you please have a try?

Thanks,
Wei

**Comment by mathiasS-hub** [comment]
Hi @weizhou0 
The new docker image runs but for some chromosomes at Step 2 (after running for some variants) it returns an error "

Error in X1_fg %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... scoreTest_SAIGE_survivalTrait_cond_sparseSigma_fast -> Score_Test_Sparse_Survival
Execution halted

I have noted that the same error happened with SAIGE and you fixed it. 

 The example log for e.g chromosome 1;

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SAIGE_0.42

loaded via a namespace (and not attached):
[1] compiler_3.5.1     Matrix_1.2-14      Rcpp_1.0.7         grid_3.5.1        
[5] RcppParallel_5.1.4 lattice_0.20-35   
$vcfFile
[1] "/reference/genepi/GWAS_release/Release11/Release11_HRCr1.1_GSA/VCF/VCF_chr1.dose.vcf.gz"

$vcfFileIndex
[1] "/reference/genepi/GWAS_release/Release11/Release11_HRCr1.1_GSA/VCF/VCF_chr1.dose.vcf.gz.tbi"

$vcfField
[1] "DS"

$bgenFile
[1] ""

$bgenFileIndex
[1] ""

$savFile
[1] ""

$savFileIndex
[1] ""

$idstoExcludeFile
[1] ""

$idstoIncludeFile
[1] ""

$rangestoExcludeFile
[1] ""

$rangestoIncludeFile
[1] ""

$chrom
[1] "1"

$start
[1] 1

$end
[1] 2.5e+08

$IsDropMissingDosages
[1] FALSE

$minMAF
[1] 0.001

$minMAC
[1] 5

$maxMAFforGroupTest
[1] 0.5

$minInfo
[1] 0

$sampleFile
[1] "/reference/genepi/GWAS_release/Release11/Release11_HRCr1.1_GSA/VCF/VCF_chr6_VCFIDsequence.txt"

$GMMATmodelFile
[1] "/working/lab_stuartma/mathiasS/MELANOMA/SURVIVAL/GATE_MIA19/out/CM_DEATH_GATE/CM_DEATH_GATE.rda"

$varianceRatioFile
[1] "/working/lab_stuartma/mathiasS/MELANOMA/SURVIVAL/GATE_MIA19/out/CM_DEATH_GATE/CM_DEATH_GATE.varianceRatio.txt"

$SAIGEOutputFile
[1] "/working/lab_stuartma/mathiasS/MELANOMA/SURVIVAL/GATE_MIA19/out/CM_DEATH_GATE/CM_DEATH_GATE_VCF_chr1.dose.vcf.gz.txt"

$numLinesOutput
[1] 100

$IsSparse
[1] TRUE

$IsOutputAFinCaseCtrl
[1] FALSE

$IsOutputNinCaseCtrl
[1] FALSE

$LOCO
[1] FALSE

$condition
[1] ""

$sparseSigmaFile
[1] ""

$groupFile
[1] ""

$kernel
[1] "linear.weighted"

$method
[1] "optimal.adj"

$weights.beta.rare
[1] "1,25"

$weights.beta.common
[1] "1,25"

$weightMAFcutoff
[1] 0.01

$r.corr
[1] "0"

$IsSingleVarinGroupTest
[1] FALSE

$minMACfordosageZerod
[1] 30

$cateVarRatioMinMACVecExclude
[1] "0.5,1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$cateVarRatioMaxMACVecInclude
[1] "1.5,2.5,3.5,4.5,5.5,10.5,20.5"

$dosageZerodCutoff
[1] 0.2

$IsOutputPvalueNAinGroupTestforBinary
[1] FALSE

$IsAccountforCasecontrolImbalanceinGroupTest
[1] TRUE

$weightsIncludeinGroupFile
[1] FALSE

$IsOutputBETASEinBurdenTest
[1] FALSE

$IsSPAfast
[1] TRUE

$NoMissingDosage
[1] TRUE

$help
[1] FALSE

weights.beta.rare  is  1 25 
weights.beta.common  is  1 25 
cateVarRatioMinMACVecExclude  is  0.5 1.5 2.5 3.5 4.5 5.5 10.5 20.5 
cateVarRatioMaxMACVecInclude  is  1.5 2.5 3.5 4.5 5.5 10.5 20.5 
single-variant association test will be performed
Any dosages <=  0.2  for genetic variants with MAC <=  30  are set to be 0
4170  samples have been used to fit the glmm null model
obj.glmm.null$LOCO:  FALSE 
Leave-one-chromosome-out option is not applied
Single variance ratio is provided, so categorical variance ratio won't be used!
variance Ratio is  0.9222388 
49639  sample IDs are found in sample file
[1] 49639     4
[1] "IID"          "IndexInModel" "IndexDose.x"  "IndexDose.y" 
4170  samples were used in fitting the NULL glmm model and are found in sample file
sparse kinship matrix is not used
NoMissingDosage is TRUE and there is no missing doages in the file
Analysis started at  1629155975 Seconds
minMAC:  5 
minMAF:  0.001 
Minimum MAF of markers to be tested is  0.001 
isCondition is  FALSE 
It is a survival trait
Fast SPA will be performed
Analyzing  559  events and  3611  censored 
isCondition is  FALSE 
Analysis started at  1629155975 Seconds
Setting genomic region 1:1:250000000
Open VCF done
To read the field DS
Number of meta lines in the vcf file (lines starting with ##): 18
Number of samples in in the vcf file: 49639
   user  system elapsed 
  3.499   0.909   3.738 
[1] 100
numPassMarker:  7 
   user  system elapsed 
  5.290   1.261   5.287 
[1] 200
numPassMarker:  19 
   user  system elapsed 
  6.980   1.399   6.940 
[1] 300
numPassMarker:  37 
   user  system elapsed 
  8.584   1.691   8.296 
[1] 400
numPassMarker:  48 
   user  system elapsed 
 10.632   2.187   9.988 
[1] 500
numPassMarker:  70 
   user  system elapsed 
 12.519   2.621  11.537 
[1] 600
numPassMarker:  87 
   user  system elapsed 
 14.020   2.777  12.910 
[1] 700
numPassMarker:  104 


Then the error " Error in X1_fg %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... scoreTest_SAIGE_survivalTrait_cond_sparseSigma_fast -> Score_Test_Sparse_Survival
Execution halted "

**Comment by sabrinacamp2** [comment]
@weizhou0 The lintools error was fixed with your most recent push of the docker, thank you!!

**Comment by weizhou0** [comment]
Hi,
Could you please try the docker image wzhou88/saige.survival:0.42.1?
Tried to fix the error in this version.

Thanks,
Wei

**Comment by mathiasS-hub** [comment]
Hi @weizhou0 
Docker image wzhou88/saige.survival:0.42.1   still returns the same error

"Error in X1_fg %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... scoreTest_SAIGE_survivalTrait_cond_sparseSigma_fast -> Score_Test_Sparse_Survival
Execution halted"

Cheers,
Mathias

**Comment by mathiasS-hub** [comment]
Hi @weizhou0 
Apart from still returning the "non-conformable" error, the docker for 0.42.1 and 0.42 were of the same size. Yet I am assuming adjustments in 0.42.1 should have made it bigger.
Cheers,
Mathias

**Comment by mathiasS-hub** [comment]
Hi @weizhou0 @jonathonl 
Please have you found a solution to the above issue?
Cheers,
Mathias

**Comment by weizhou0** [comment]
Hi @mathiasS-hub, 

Please see our updated conda env file and the steps.

https://github.com/weizhou0/GATE#install-gate-using-the-conda-environment

Thanks,
Wei
