### ISSUE TITLE
phenoCol vs eventTimeCol

### ISSUE THREAD

**Issue by sabrinacamp2** [weizhou0/GATE#8]
Hi!

Thank you for making this tool. I am trying to understand where to put the survival time I have and then the status (whether the event occurred, 1 for observed 0 for censored).

The documentation in the readme describes the eventTimeCol as something like age at diagnosis. Would I then be putting the "status" information in the phenoCol? 

Thank you,
Sabrina

**Comment by alldayscientess** [comment]
Interested to know the answer to this question as well!

**Comment by weizhou0** [comment]
Hi @alldayscientess and @sabrinacamp2, 

Your understanding is correct.  phenoCol is for event status (0 or 1 is for censored or event)

Thanks,
Wei
