### ISSUE TITLE
Error in X1_fg %*% Z : non-conformable arguments

### ISSUE THREAD

**Issue by mathiasS-hub** [weizhou0/GATE#9]
Hi, 
Is anyone else still experiencing this error below with the current version 0.42.1 or it is just me?
Error in X1_fg %*% Z : non-conformable arguments
Calls: SPAGMMATtest ... scoreTest_SAIGE_survivalTrait_cond_sparseSigma_fast -> Score_Test_Sparse_Survival
Execution halted "

I would be glad if anyone provides us with a solution.
Cheers,
Mathias

**Comment by BioSand** [comment]
@weizhou0 @mathiasS-hub @weizhouUMICH 

Hi all, 
have this problem solved ?
having a similar issue. 

Best, 
Santiago

**Comment by mathiasS-hub** [comment]
Hi @BioSand not yet. But I think @weizhou0 @weizhouUMICH is working on it.
Cheers,
Mathias

**Comment by weizhou0** [comment]
Hi @mathiasS-hub and @BioSand, 

Sorry about the late reply. 
The issue has been fixed in the version 0.44.1. 

Thanks,
Wei
